### ISSUE TITLE
Add more features to species list service

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_webservices#10]
Species list service now supports inserting lists, getting user lists, getting species of a list features. I need to add remove lists, remove species from a list features to complete the set of features. Since each list is related to a user, some users may want to keep their lists private or some may want to keep those public. So I will keep option to support that feature.

**Comment by abusalehmdtayeen** [comment]
Implemented the following features to species list services:
1. Inserting species to an existing list.
2. Remove species from an existing list.
3. Remove a complete list.
4. Concept of public and private lists. Retrieval of public lists by any user.

**Comment by hdliv** [comment]
moving this to done

**Comment by arlin** [comment]
@hdliv , if you did some tests on this, please give us a sentence or 2 to describe

**Comment by hdliv** [comment]
@arlin I spoke to @abusalehmdtayeen and you and i tested these last week: https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md

**Comment by hdliv** [comment]
@arlin will move back and test again

**Comment by hdliv** [comment]
all working
