### ISSUE TITLE
A service to find whether a species has genome sequence in NCBI

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_webservices#11]

**Comment by arlin** [comment]
The complete workflow for "provide the tree for all species in taxon T with genomes in NCBI" is implemented in Perl here:   https://github.com/arlin/sample_taxa/tree/master/perl 

I hope that is helpful.

**Comment by abusalehmdtayeen** [comment]
@arlin, Thanks for the link. The scripts really helped me to figure out which API's of NCBI to use for this use case since there are several of them. I have finished coding the module for this service.

**Comment by arlin** [comment]
I have tested this with several taxa, e.g., 
http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/ncbi/genome_species?taxon=Felidae

This works.  Thanks.   It will be useful to have.
