### ISSUE TITLE
use induced subtree, not subtree

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#12]
Change the web service so that it only gets the induced subtree.

**Comment by abusalehmdtayeen** [comment]
@arlin: I have modified the get tree service to use only induced_subtree method of Open Tree. Now you should be able to get reduced size tree. Please test the app now. We don't know much about the behaviour of induced_subtree method. It might happen that in some cases the method will fail. Let me know about these cases. I will verify it with direct Open Tree service call.

**Comment by arlin** [comment]
Yes, this appears to be fixed.   I have not experienced a single failure yet.  thanks!

**Comment by hdliv** [comment]
@arlin @abusalehmdtayeen I tested the mosquito photo a few days ago and tested again and we get a tree of the 3 and a 'cut-off' tree with the same.
