### ISSUE TITLE
Modify taxon_to_species service code to fix "Felidae" behavior

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_webservices#13]
reference: https://github.com/phylotastic/phylo_webservices/issues/9

**Comment by abusalehmdtayeen** [comment]
Modified taxon to species service to fix "Felidae" behaviour. Also implemented cache to improve the service. Now for higher taxon inputs, in the first request the response time may be long , but in the next requests it will be faster.

**Comment by arlin** [comment]
this seems to be fixed.  Is it time to move this to "in review"?

**Comment by arlin** [comment]
I have tested this and it is fixed for Felidae. Thanks!
