### ISSUE TITLE
Test Web Service : Create Test Function and Test Cases for Find Scientific Names on web pages

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/phylo_webservices#18]

**Comment by arlin** [comment]
Same comment on issubset applies as for #21.  

instead of referring to "Web Service 1's result", it would be more informative to explain that this is a service to scrape names from a URL, e.g.,, "the result of web service 1 (scrape names from URL using GNRD) is .  . ."

**Comment by thanhnh-infinity** [comment]
Yes, I will make it more detail for message

**Comment by arlin** [comment]
The remaining task is to replace the "subset" method with the desired "equals" method when testing the return value against the expected return value for a service.  I'm sure you can solve the problem with sorting.

**Comment by thanhnh-infinity** [comment]
I think ,now, Testing Web Services are transferred to @abusalehmdtayeen . He will continue developing this task. @abusalehmdtayeen , could you take a look that Dr @arlin's suggest
