### ISSUE TITLE
Test Web Service : Create Test Function and Test Cases for Find Scientific Names on free-form text

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/phylo_webservices#19]

**Comment by arlin** [comment]
same comments as for #18

**Comment by arlin** [comment]
The remaining task is to replace the "subset" method with the desired "equals" method when testing the return value against the expected return value for a service.  I'm sure you can solve the problem with sorting.

**Comment by thanhnh-infinity** [comment]
I think ,now, Testing Web Services are transferred to @abusalehmdtayeen . He will continue developing this task. @abusalehmdtayeen , could you take a look that Dr @arlin's suggest
