### ISSUE TITLE
Test Web Service : Create Test Function and Test Case for Resolve Scientific Names with GNR TNRS (GET and POST method)

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/phylo_webservices#21]

**Comment by arlin** [comment]
I reviewed this code today.   Two comments: 

1.  WS_N_HEADER is defined for N = 1 to 8, but it is always the same.   Therefore the following code does not produce an error: 

"requests.get(WS_4_RESOURCES_URL_GET, params=encoded_param_structure, headers=WS_3_HEADER)"

however, this is not a good practice.  If the header is always going to be the same, then just define it once rather than 8 times.  If not, then be sure to use the correct header in each get request.  

2.  Why are you checking for issubset rather than isequal?   Don't we want to set up the tests so that success is defined as getting exactly the expected result?  

if (not set_expected_ouput.issubset(set_result)):

**Comment by thanhnh-infinity** [comment]
Hi @arlin 

1. WS_N_HEADER is header for HTTP request for each web service. Because right now, these web services are "application/json", so you saw they are the same. But if the web service (for example WS 1) changes the header to "application/xml or plain-text", it is not similar with the rest. In order to guarantee this case (when WS changes the format and data type for input and output), each Web service should have private WS_HEADER. I will check and fix to make sure that WS N will only use HEADER N. The code you posted below is mistake in my coding, it should be WS_4_HEADER

2. I am checking for subset rather than equal because : for example, with WS 2, get scientific names from text. When input a text "abcxyz...", and we can get the collection of scientific names , they could be [A,B,C] or [B,A,C] or [C,A,B]. If we use equal, it means they compare with absolute value, [A,B,C] is equal [A,B,C] but [A,B,C] is NOT equal [B,A,C]. And in our case, I think that we can define expected value such as [C,B,A], and when compare with above results from Web service, we can check that  [C,B,A] is subset of [A,B,C] or [B,A,C] or [C,A,B].  

In my use case I wrote in runTest.py, may be It is not full enough for expected value. However expected value is defined by user case writers so I think we can change it as we expected.

**Comment by arlin** [comment]
I'm sorry for letting this slip.  The correct behavior is to test for equality of sets, where  [A,B,C] setequals [A,C,B].    I'm sure that you can find setequals methods in Python somewhere.  If that is not easy to find, then just compare expected.sort to result.sort.

**Comment by arlin** [comment]
The remaining task is to replace the "subset" method with the desired "equals" method when testing the return value against the expected return value for a service.  I'm sure you can solve the problem with sorting.

**Comment by thanhnh-infinity** [comment]
I think ,now, Testing Web Services are transferred to @abusalehmdtayeen . He will continue developing this task. @abusalehmdtayeen , could you take a look that Dr @arlin's suggest

**Comment by thanhnh-infinity** [comment]
I think ,now, Testing Web Services are transferred to @abusalehmdtayeen . He will continue developing this task. @abusalehmdtayeen , could you take a look that Dr @arlin's suggest

**Comment by thanhnh-infinity** [comment]
I think ,now, Testing Web Services are transferred to @abusalehmdtayeen . He will continue developing this task. @abusalehmdtayeen , could you take a look that Dr @arlin's suggest
