### ISSUE TITLE
Test Web Service : Create Test Function and Test Case for Get Phylogenetic Trees from Open Tree of Life (GET and POST method)

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/phylo_webservices#22]

**Comment by arlin** [comment]
The remaining task is to replace the "subset" method with the desired "equals" method when testing the return value against the expected return value for a service.  I'm sure you can solve the problem with sorting.

**Comment by thanhnh-infinity** [comment]
I think ,now, Testing Web Services are transferred to @abusalehmdtayeen . He will continue developing this task. @abusalehmdtayeen , could you take a look that Dr @arlin's suggest

**Comment by abusalehmdtayeen** [comment]
Ok, @thanhnh-infinity , I will fix those.
