### ISSUE TITLE
Change species list service APIs

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_webservices#23]
Change the get_list API according to the document sent by Dail

**Comment by abusalehmdtayeen** [comment]
Changed the service API based on new requirements.

**Comment by arlin** [comment]
Please describe the changes so that they can be reviewed.

**Comment by abusalehmdtayeen** [comment]
Here is a summary of the changes I made:

1. There is only one API to get list information instead of get user lists and get public lists API. There is also no get_species API. You have to use the combination of two optional parameters to get meta-data and species collection.

2. To get a private list a user must authenticate by providing both his user_id (email) and valid access token.

3. No authentication is required to insert lists or insert species to an existing list. But to replace or remove species and to remove a list you need to provide the access token for the user.

4. The APIs are now more responsive by providing you with appropriate error messages.

You can find the API description in https://github.com/phylotastic/phylo_services_docs/blob/master/SpeciesListServer/SpeciesListServicesDescription.md

**Comment by abusalehmdtayeen** [comment]
@hdliv , You can close this issue. This was completed more than a month ago.
