### ISSUE TITLE
Attach metadata info in each web service result

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_webservices#34]
Web services should be able to give metadata output along with the result so that user knows exactly where the result came from

**Comment by arlin** [comment]
@abusalehmdtayeen, @hdliv  and I were discussing this over the past week.  @hdliv would like to work with you on this.  

For a good example, see @dimus  description here http://gnrd.globalnames.org/api

**Comment by arlin** [comment]
@abusalehmdtayeen, I am trying to update this ticket.  Did the metadata get reviewed during the web services testing last fall?

**Comment by abusalehmdtayeen** [comment]
Yes. We have metadata for all web services. I am closing this issue.
