### ISSUE TITLE
metadata for "Resolve Scientific Names with GNR TNRS"

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#43]
For web service 4, add metadata to JSON returned by service.  GNRD provides an excellent example of this. The metadata should include

* all of the search parameter settings. See below.
* the number of names returned
* the date and time of execution
* the URL of this service
* the URL for the docs for this service

Parameter settings are reported already by GNRD resolver (see http://resolver.globalnames.org/api). We just need to carry these over into our results.

**Comment by arlin** [comment]
See the comment to #6.  Please remove the comments and place the query string inside the json.

**Comment by abusalehmdtayeen** [comment]
Done.
