### ISSUE TITLE
add metadata to "Get Phylogenetic Trees from Open Tree of Life"

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#44]
For web service 5, add metadata to the information returned by service.  The metadata should include

* the number of tips
* the version of the synth tree (synth_id in tree_of_life/about)
* the list of supporting studies (see below)
* the date and time of execution (see below)
* the URL of this service
* the URL for the docs for this service

@abusalehmdtayeen  is already including a timestamp as a comment with the form `// 20161221142133`.  This needs to be turned into a valid JSON expression. 

The list of supporting studies is already included in the JSON returned by the OpenTree service.

**Comment by abusalehmdtayeen** [comment]
Done.

**Comment by arlin** [comment]
I'm sorry for taking so long to get to this.   I see two small issues.  One of them is that there is a missing space after induced_subtree in "inference_method": "induced_subtreefrom synthetic tree version opentree8.0".  

Second, I think we should call the synth tree version  "synth_id" rather than "synth_tree_version", on the grounds that this is what OpenTree uses.  I have requested clarification from OT about whether they intend to anchor all their terms in a formal vocabulary.

**Comment by abusalehmdtayeen** [comment]
Corrected the issues.
