### ISSUE TITLE
metadata for "Get all Species from a Taxon"

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#45]
For web service 6, add metadata to the information returned by service. The metadata should include
   * input query
   * list of taxa returned
   * number of taxa returned
   * date
   * source
   * version of the source

**Comment by hdliv** [comment]
For web service 6,  add metadata to the information returned by service.  The metadata should include

   * input query
   * list of taxa returned
   * number of taxa returned
   * date
   * source
   * version of the source

**Comment by arlin** [comment]
@hdliv, can you put that into the description for this ticket instead of a comment, please?

**Comment by hdliv** [comment]
@arlin done

**Comment by abusalehmdtayeen** [comment]
Done

**Comment by arlin** [comment]
Good, I like this.  

`{
  "execution_time": "0.33",
  "status_code": 200,
  "creation_time": "2017-03-08T14:41:13.884198",
  "taxon": "Canidae",
  "total_names": 166,
  "source_urls": [
    "https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy"
  ],
  "source_version": "ott2.9draft12",
  "service_url": "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/ts/all_species?taxon=Canidae",
  "message": "Success",
  "species": [
    "Aelurodon taxoides",
    "Aelurodon asthenostylus",
...
],
  "service_documentation": "https://github.com/phylotastic/phylo_services_docs/blob/master/ServiceDescription/PhyloServicesDescription.md#web-service-6"
}`

The part that needs more work is how we describe the sources.  

The OTT link (https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-Taxonomy) must be out of date or something because it tries to create a new page.  If we are wrapping OT's services, then *our documentation* needs to say that clearly, and it should refer to the service we are wrapping.   

For now, please do the following: 
* remove "source_urls" and "source_version" because this is confusing
* change the order so that "service_documentation" appears right after "service_url"

**Comment by abusalehmdtayeen** [comment]
@arlin, "source_urls" and "source_version" properties have been removed. 
From the JSON specification at http://www.json.org/: "An object is an unordered set of name/value pairs". As a consequence, JSON libraries are free to rearrange the order of the elements as they see fit. So I can not control the order of  "service_documentation"  and "service_url".
