### ISSUE TITLE
design common-names service

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#46]
For various uses, especially educational ones, it will be useful to have a common names service that maps common names to formal names and back.  NCBI has numerous common names in its taxonomy, which can be accessed via an API or downloaded by ftp.  @hyanwong already has built a mapping. 

1.  consider requirements for a common-names service.  what use-cases must it support?  what operations must it provide? 

2.  assess available sources of information, and consider strategic collaborators. 

3.  sketch a plan for a web service and get feedback on the plan.

**Comment by hyanwong** [comment]
My mapping simply uses EOL common names, which are culled from many sources. But this does mean they are multilingual. The key part is mapping from EOL ids to e.g. OTT identifiers, which I have done.
