### ISSUE TITLE
find out why some EOL images are not acquired

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#48]
Go to the dev server, choose the Marine vs. terrestrial mammals list, get a tree, and load the images.  The images are missing for Trichechus manatus and Balaenoptera acutorostrata.  

However, images are available for both of these species at EOL.  

Find out why this is happening.  If it is a bug in our services, write a ticket for that.  If it is a bug in EOL services, write a ticket for that.  If it is not a bug, put an explanation in the FAQ.

**Comment by abusalehmdtayeen** [comment]
@arlin, I found a small bug in our image service. I have fixed it. Now you should be able to see images of those two species.

**Comment by arlin** [comment]
Thanks!  Closing this.  Looks good.
