### ISSUE TITLE
phylomatic tree service

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_webservices#49]
Wrap phylomatic into a service which will work as an alternative tree service for phylotastic.

**Comment by arlin** [comment]
Phylomatic offers 3 different plant trees and 1 mammal tree.  The examples in the docs suggest that you are using the mammals tree.  Can you confirm that @abusalehmdtayeen?

**Comment by abusalehmdtayeen** [comment]
@arlin, In the documentation, I have added another example which uses one of the plant trees. Actually the choice of mega tree will depend on the list of species that are given as input. If most of the species are plant species than the service will use one of the plant mega trees to get the output  tree. Otherwise, mammals mega tree will be used.
