### ISSUE TITLE
phyloT web service

### ISSUE THREAD

**Issue by abusalehmdtayeen** [phylotastic/phylo_webservices#50]
Create a web service using phyloT tree generation engine API.

**Comment by abusalehmdtayeen** [comment]
Finished implementation of the new web service to get phylogenetic trees from phyloT. 
https://github.com/phylotastic/phylo_services_docs/blob/master/ServiceDescription/PhyloServicesDescription.md#web-service-19

**Comment by arlin** [comment]
This is good.  I would like to make a few small suggestions.  
1.  remove the comments
2. put the query string in the return
3. modify the docs to explain how PhyloT works.  One simple way to do this is to change the service description field to 

"Service Description: A service to get a taxonomic tree from the NCBI taxonomy using phyloT (http://phylot.biobyte.de/)"

**Comment by abusalehmdtayeen** [comment]
Done.
