### ISSUE TITLE
Wrong content-type

### ISSUE THREAD

**Issue by jar398** [phylotastic/phylo_webservices#51]
At least one of the services (`tnrs/ot/resolve`) is generating the wrong content-type in the response.  E.g.

```
curl -D - "http://phylo.cs.nmsu.edu:5004/phylotastic_ws/tnrs/ot/resolve?names=Pseudacris%20crucifer”
```

gives the following headers

```
HTTP/1.1 200 OK
Content-Length: 776
Server: CherryPy/4.0.0
Access-Control-Allow-Credentials: true
Date: Tue, 19 Sep 2017 19:46:00 GMT
Access-Control-Allow-Origin: *
Content-Type: text/html;charset=utf-8
```

The content-type ought to be `application/json`, as the documentation says. See "Output Format" at https://github.com/phylotastic/phylo_services_docs/blob/master/ServiceDescription/PhyloServicesDescription.md

**Comment by abusalehmdtayeen** [comment]
@jar398, The content-type issue has been resolved. I found the same problem for some other services too and fixed them all. You can check. Thanks.

**Comment by jar398** [comment]
Excellent, thanks. Checks out for that one service and I assume it will work with the others - if it doesn't then I will re-open this issue.
