### ISSUE TITLE
Getting taxonomy from NCBI is failing. 

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylo_webservices#60]
CRAN will pull rphylotastic by June 30 if we don't fix this in the examples: https://cran.r-project.org/web/checks/check_results_rphylotastic.html.

It'a actually a problem with the service that gets info from NCBI: it's now returning

```
{"message": "ItoL upload error:ITOL VERSION 2 BATCH IS NO LONGER AVAILABLE. PLEASE USE THE CURRENT VERSION.\n"}
```

when calling `http://phylo.cs.nmsu.edu:5004/phylotastic_ws/gt/pt/get_tree?taxa=Setophaga striata|Setophaga magnolia|Setophaga angelae|Setophaga plumbea|Setophaga virens`, our service 19.

**Comment by abusalehmdtayeen** [comment]
@bomeara , I checked ITOL's new API and tried to fix the service. But they have changed it significantly. The workflow that I used to follow to get a tree using PhyloT is no longer possible. So we need to discontinue using this service.

**Comment by bomeara** [comment]
Ok. Thanks. I'm deleting it from rphylotastic. Could you delete it from our services and the python package? We should also make sure @arlin notes this in the paper writing.

**Comment by arlin** [comment]
@bomeara, does this relate to the issues that I found in the vignettes?

**Comment by arlin** [comment]
@abusalehmdtayeen could you please provide an update on the status of this?

**Comment by arlin** [comment]
So, if we have removed the service, and references to the service, we can close this ticket.  @abusalehmdtayeen, if that is true, could you please close this?
