### ISSUE TITLE
Identify and fix scaling bottleneck

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#62]
From load testing results here:

https://docs.google.com/document/d/1mgal-qCKOlGGrHC0EsEve2KzxP_LCy_q2Y2_ytOeM6c/edit#heading=h.fzugdk5hu7q2

we believe that there is a bottleneck in scaling services at the level of the NMSU wrapper or the underlying R function calls.

Find out what is wrong, and fix things so that we can support 100 concurrent scaling threads.

**Comment by arlin** [comment]
From load testing results here:

https://docs.google.com/document/d/1mgal-qCKOlGGrHC0EsEve2KzxP_LCy_q2Y2_ytOeM6c/edit#heading=h.fzugdk5hu7q2

we believe that there is a bottleneck in scaling services at the level of the NMSU wrapper or the underlying R function calls.   

Find out what is wrong, and fix things so that we can support 100 concurrent scaling threads.

**Comment by abusalehmdtayeen** [comment]
I have replaced the old Python-to-R interface with a new one.  The new interface will be able to handle multiple connections to datelife R library. As a result, the datelife service will now scale better.
