### ISSUE TITLE
expand test of get studies

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#67]
In test_md_studies.py, there are a couple of tests that do not actually test for correctness of the return value.  See the notes that say "Insert: ..." at lines 25 and 33. 

Use the inputs in example_1 and example_2 to figure out what is the correct answer (see test_md_get_studies.py for examples of this).   Then, expand the test to check that, in each case, we get the right value for at least one of the implicated studies.

**Comment by abusalehmdtayeen** [comment]
Done

**Comment by arlin** [comment]
thanks @abusalehmdtayeen
