### ISSUE TITLE
remove tryphy dependency

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#69]
Some of the files in the web services test suite depend on source files in a separate repo, the tryphy repo.  We want to remove this dependency.  

In each case, identify the source file in the test code, copy it into the webservices repo, then rewrite the test so that it points to the new copy.  I did a grep on "tryphy" and there are only two files like this: 

- [ ]  test_fn_tf_names_url.py
- [ ] test_fn_gnrd_names.py

**Comment by abusalehmdtayeen** [comment]
Done.

**Comment by arlin** [comment]
is the test in the first file currently being skipped?

**Comment by arlin** [comment]
I'm closing this but I will raise the issue about QOS vs. CI in the chat room.
