### ISSUE TITLE
Remove singleton nodes

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylo_webservices#71]
For all trees returned, allow the collapse of singleton nodes (nodes with one descendant only). Esp for javascript tree viz, such nodes can be annoying. The thing to watch is how names propagate on collapse (in a series of singleton nodes, typically each node has a name -- we probably want either the name on the tipmost or rootmost node (I'd argue for rootmost)).

**Comment by LunaSare** [comment]
From r we use the function `ape::collapse.singles()`, but that uses a phylo object as input

**Comment by abusalehmdtayeen** [comment]
Its done.
