### ISSUE TITLE
ottids in returned tree

### ISSUE THREAD

**Issue by bomeara** [phylotastic/phylo_webservices#73]
https://github.com/phylotastic/phylo_services_docs/tree/master/ServiceDescription#ot has an option for ottid. There are two issues with this:

* The description is confusing: "a boolean value to specify whether to remove ott ids from the tree." -- so if true, it should remove... but it does the opposite. So I'd say "whether to *keep* ott ids"

* If you do choose to get rid of ottids, it also replaces underscores with spaces (which other tree viewers then convert to spaces, which then get collapsed. I'd just keep as underscores, whether or not ott ids are included; perhaps have a different argument for underscores to spaces or not.

**Comment by abusalehmdtayeen** [comment]
@bomeara , I have updated the document  and made the changes in code as you suggested. It does not remove underscores now. Can you please test and close the issue if it is done?

**Comment by bomeara** [comment]
It's better, but still an issue with a few names: 

<img width="585" alt="Screen Shot 2019-04-08 at 10 29 41 AM" src="https://user-images.githubusercontent.com/1612612/55732332-cd696800-59e9-11e9-8233-7e2cd5456998.png">

**Comment by bomeara** [comment]
btw, thanks for fixing the singleton node issue, too
