### ISSUE TITLE
OToL_wrapper_Tree returning no data from server

### ISSUE THREAD

**Issue by patrickdlandy** [phylotastic/phylo_webservices#76]
The following GET requests are returning no data from the server as of April 15th, 2020. The OToL_wrapper_Tree service worked for me as recently as April 10th.

-Example given for OToL_wrapper_Tree sent as GET request on Postman: (no response): https://phylo.cs.nmsu.edu/phylotastic_ws/gt/ot/get_tree?taxa=Panthera%20pardus|Taxidea%20taxus|Lutra%20lutra|Canis%20lupus|Mustela%20altaica

-My own GET request, sent using cURL in PHP: (cURL error is "Empty reply from server" after 1 minute): https://phylo.cs.nmsu.edu/phylotastic_ws/gt/ot/get_tree?taxa=Clarias%20macrocephalus|Mesopodopsis%20orientalis|Paralithodes%20camtschaticus|Litopenaeus%20stylirostris|Portunidae|Mytilus%20edulis|Lepomis%20macrochirus|Metapenaeus%20monoceros|Strombus%20gracilior|Callinectes%20sapidus|Nephropidae|Plesionika%20martia|Coryphaena%20hippurus|Rachycentron|Pelodiscus%20sinensis|Esox%20lucius|Coregonus%20artedi|Macrobrachium%20rosenbergii|Acipenser%20transmontanus|Mytilus%20coruscus|Loligo|Sergestidae|Sebastes%20norvegicus|Sepia%20officinalis|Pecten%20maximus|Melanogrammus%20aeglefinus|Crassostrea%20gigas|Mytilus|Strombidae|Mullus%20barbatus|Portunus%20pelagicus|Rachycentron%20canadum|Sardinops%20melanosticus|Macrobrachium%20malcolmsonii|Macrobrachium|Strombus%20galeatus|Penaeus%20latisulcatus|Pandalus|Penaeus%20semisulcatus|Parapenaeus%20australiensis|Gadus%20morhua|Cancer%20magister|Crassostrea|Haliporoides%20sibogae|Pangasianodon%20hypophthalmus|Litopenaeus%20vannamei|Ostrea|Cancridae|Trachurus%20trachurus|Ommastrephidae|Clarias%20gariepinus|Rhomboplites|Oncorhynchus%20mykiss|Epinephelus%20akaara|Squalus%20acanthias|Homarus%20gammarus|Pandalus%20borealis|Crassostrea%20virginica|Notropis%20atherinoides|Panulirus%20argus|Penaeus%20monodon|Perca%20flavescens|Osmerus%20mordax|Penaeidae|Engraulis%20encrasicolus|Oncorhynchus%20gorbuscha|Ostrea%20edulis|Atherina%20boyeri|Sander%20vitreus|Pagrus%20major|Scylla%20serrata|Oncorhynchus%20tshawytscha|Thunnus%20maccoyii|Esox%20masquinongy|Ocyurus%20chrysurus|Sardina%20pilchardus|Thunnus%20albacares|Oncorhynchus%20nerka|Octopus%20vulgaris|Dicentrarchus%20labrax|Mytilus%20galloprovincialis|Acetes|Perna%20viridis|Sepiidae|Sparus%20aurata|Boops%20boops|Gadus%20macrocephalus|Ocyurus|Metapenaeus%20endeavouri|Metapenaeus%20macleayi|Eriocheir%20sinensis|Chionoecetes|Merluccius%20capensis|Lutjanus|Solea%20solea|Palinuridae|Salmo%20trutta|Clarias%20batrachus|Scophthalmus%20maximus|Oreochromis%20niloticus|Penaeus%20merguiensis|Cyprinus%20carpio|Rhomboplites%20aurorubens|Solea%20senegalensis|Chamelea%20gallina|Eopsetta%20jordani|Nephrops%20norvegicus|Octopodidae|Fundulus%20heteroclitus|Cancer%20pagurus|Thunnus%20alalunga|Salmo%20salar|Sciaenops%20ocellatus|Ictalurus%20punctatus|Pomoxis%20nigromaculatus|Loligo%20vulgaris|Acetes%20indicus|Crangon%20crangon|Perna|Procambarus%20clarkii|Parapenaeus%20longirostris|Coregonus%20clupeaformis|Haliotis|Jasus%20edwardsii||Veneridae|Clupea%20harengus|Paralichthys%20olivaceus|Pleoticus%20muelleri|Merluccius%20merluccius|Siniperca%20chuatsi|Homarus%20americanus|Sander%20canadensis|Lateolabrax%20japonicus|Lates%20calcarifer|Crassostrea%20rhizophorae|Perna%20canaliculus|Pectinidae|Tinca%20tinca|Thunnus%20obesus|Penaeus%20esculentus|Melicertus%20plebejus|Spicara%20smaris|Paracentrotus%20lividus|Lithodidae

**Comment by abusalehmdtayeen** [comment]
Hi @patrickdlandy , the OToL_wrapper_Tree service depends on the OpenTreeofLife (OToL) API which was down for a couple of days. This is why you did not get any response from the service. Although OToL API is working now, some of the examples in our documentation is not working at this moment. We will have to check whether there is any change to the OToL API which is causing this problem. Thanks for notifying us. We will address this and get back to you soon.

**Comment by abusalehmdtayeen** [comment]
Hi  @patrickdlandy , We have resolved the problem. Your long GET request now works. I am closing this issue. Please feel free to open another issue if you find problem with any other services. Thanks.

**Comment by patrickdlandy** [comment]
Working now.  Thanks!
