### ISSUE TITLE
investigate "Felidae" behavior

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#9]
When I request species from taxon "Felidae" (cat family) using the web tool, I get a list of 44 species that are all from *extinct* genera (Adelphailurus, Dinofelis, Homotherium, Machairodus, Megantereon, Miracinonyx, Nimravides, Pontosmilus, Pratifelis, Proailurus, Pseudaelurus, Sivapanthera, Smilodon).  So the tree is always empty.  There are 30 to 40 living cat species including lion, tiger, cheetah and so on.  

The issue is to track down what is happening here, and specifically to find out why I am not seeing all the familiar extant cat species-- Felis silvestris, Panthera leo, Panthera pardus and so on.

**Comment by abusalehmdtayeen** [comment]
@arlin : I have done a detail analysis on the behaviour of the service on Felidae input. I found that it is not a bug of the service, but rather ​a problem of Open Tree API response. You can find a brief report of the analysis in https://github.com/phylotastic/phylo_services_docs/blob/master/BugReports/Taxon%20to%20species%20service%20bug%20report.md

**Comment by arlin** [comment]
Thanks for the analysis and the workflow diagram!  Lets continue discussion  in the chat room.
